# react-app-chart/values.yaml
replicaCount: 2

image:
  repository: myreactappacr.azurecr.io/my-react-app
  pullPolicy: Always
  tag: "66"  # Change to your latest pushed tag

serviceAccount:
  create: false
  name: ""

service:
  type: LoadBalancer  # Changed from ClusterIP to expose externally
  port: 8080

ingress:
  enabled: false  # Disable for now unless you're setting up ingress controller + DNS
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: my-react-app.contoso.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - my-react-app.contoso.com
      secretName: my-react-app-tls

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

podSecurityContext:
  fsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# 🔧 Add volumeMounts and volumes to support /tmp being writable
volumeMounts:
  - name: temp-volume
    mountPath: /tmp

volumes:
  - name: temp-volume
    emptyDir: {}
