# react-app-chart/values.yaml
replicaCount: 2

image:
  repository: myreactappacr.azurecr.io/my-react-app
  pullPolicy: Always
  tag: "latest"

# Add service account configuration to prevent errors
serviceAccount:
  create: false  # Set to true if your app needs Kubernetes API access
  name: ""

service:
  type: ClusterIP  # Consider LoadBalancer for direct external access during development
  port: 8080

ingress:
  enabled: true
  className: "nginx"  # Add this new field
  annotations: 
    # Remove the deprecated annotation
    # kubernetes.io/ingress.class: nginx ← Remove this
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Keep other annotations
  hosts:
    - host: my-react-app.contoso.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - my-react-app.contoso.com
      secretName: my-react-app-tls

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

# Add pod security context (recommended)
podSecurityContext:
  fsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

# Add security context for containers
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000